[BIA-1266]: Consider optional data - epp_CandidateSurveyDim
Ed-Fi-Exchange-OSS/API-to-AMT-Data-Lake pull request #100
Opened 2022-12-20 15:03 UTC by jegasape

- Consider optional data - epp_CandidateSurveyDim

2022-12-20 19:31 UTC, DavidJGapCR commented
I am getting this error when I run the app:
![image](https://user-images.githubusercontent.com/16614428/208750558-450cbf36-9d2c-46e4-9dbc-6cad3b0b28b2.png)

Remember that when you set a value for recordPath, you have to set a value for recordMeta as well. I think this is why we are getting this error.
![image](https://user-images.githubusercontent.com/16614428/208750865-ec11d407-a94b-4dfe-b895-a27fbf9f7786.png)

2022-12-20 19:36 UTC, DavidJGapCR requested changes
I am not able to run the app.

2022-12-21 01:13 UTC, jegasape commented
The candidateSurveyDim.parquet file is generated correctly, check your configuration and environment.

![Screenshot from 2022-12-20 20-03-33](https://user-images.githubusercontent.com/44595343/208797025-9c4e4202-9a27-4595-bb14-f02afca64888.png)

2022-12-21 21:11 UTC, DavidJGapCR approved these changes

2022-12-21 21:12 UTC, merged