[BIA-1231]: Handle parquet creation scripts errors
Ed-Fi-Exchange-OSS/API-to-AMT-Data-Lake pull request #94
Opened 2022-12-08 15:15 UTC by jegasape

- Handle parquet creation scripts errors

2022-12-14 02:21 UTC, jleiva-gap requested changes
The logger is not registering the stacktrace. The process prints the trace, but you cannot read it from the logger.
![image](https://user-images.githubusercontent.com/56046999/207489267-aa6660af-cfee-486e-a5c8-793e380223ae.png)

We could try with traceback.format_exc().

2022-12-14 15:07 UTC, jegasape commented on src/dagster_data_lake/dagster_data_lake/ops/api.py
> +        logger.error(f"Error: {ex}", exc_info=True)
I will be making the changes shortly to use traceback.format_exc().

2022-12-14 20:19 UTC, jegasape commented on src/dagster_data_lake/dagster_data_lake/ops/api.py
> +        logger.error(f"Error: {ex}", exc_info=True)
Done.

2022-12-15 14:43 UTC, jleiva-gap approved these changes

2022-12-15 14:43 UTC, merged